-- Raio-X Comercial — tabela inicial / migração segura
create table if not exists raio_x_leads (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text,
    whatsapp text,
    city text,
    experience text,
    works_protection text,
    contacts_month integer,
    conversations_month integer,
    quotes_month integer,
    sales_month integer,
    gain_per_sale numeric,
    discount_pct numeric,
    discount_label text,
    target_sales integer,
    lead_source text,
    source_conversion_factor numeric,
    source_quote_sale_rate numeric,
    required_contacts numeric,
    additional_contacts numeric,
    rate_contact_conversation numeric,
    rate_conversation_quote numeric,
    rate_quote_sale numeric,
    rate_contact_sale numeric,
    contacts_per_sale numeric,
    bottleneck text,
    focus_stage text,
    needed_rate numeric,
    current_revenue numeric,
    target_revenue numeric,
    extra_revenue numeric,
    profile_name text,
    profile_level integer,
    source text
);

alter table raio_x_leads add column if not exists lead_source text;
alter table raio_x_leads add column if not exists source_conversion_factor numeric;
alter table raio_x_leads add column if not exists source_quote_sale_rate numeric;
alter table raio_x_leads add column if not exists required_contacts numeric;
alter table raio_x_leads add column if not exists additional_contacts numeric;
alter table raio_x_leads add column if not exists focus_stage text;
alter table raio_x_leads add column if not exists discount_pct numeric;
alter table raio_x_leads add column if not exists discount_label text;
alter table raio_x_leads add column if not exists rate_contact_sale numeric;
alter table raio_x_leads add column if not exists contacts_per_sale numeric;
alter table raio_x_leads add column if not exists profile_name text;
alter table raio_x_leads add column if not exists profile_level integer;
