
create table if not exists public.raio_x_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  whatsapp text not null,
  city text,
  experience text,
  works_protection text,
  contacts_month integer,
  conversations_month integer,
  quotes_month integer,
  sales_month integer,
  gain_per_sale numeric,
  target_sales integer,
  rate_contact_conversation numeric,
  rate_conversation_quote numeric,
  rate_quote_sale numeric,
  bottleneck text,
  focus_stage text,
  needed_rate numeric,
  current_revenue numeric,
  target_revenue numeric,
  extra_revenue numeric,
  source text
);

alter table public.raio_x_leads enable row level security;

-- Para o MVP, recomendamos inserir pelo servidor com a service role key.
-- Se usar a anon key diretamente, crie uma policy de INSERT adequada
-- e NUNCA exponha uma service role key no frontend.
